baseURL = "https://delacruz.dev/"
languageCode = "en-us"
title = "Dani de la Cruz"
theme = "delacruz"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[permalinks]
	mentorship = "/:filename/"

[params]
    author = "Daniel de la Cruz"
    description = "JavaScript Software Engineer and Developer Mentor"
    githubUsername = "d4nidev"
    accent = "#00d1b2"
    showBorder = true
    backgroundColor = "#f7f4ef"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["javascript", "typescript", "html", "css"]
