baseURL = "https://delacruz.dev/"
languageCode = "en-us"
title = "Dani de la Cruz"
theme = "delacruz"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[permalinks]
	mentorship = "/:filename/"

[params]
    author = "Daniel de la Cruz"
    description = "JavaScript Software Engineer and Developer Mentor"
    githubUsername = "d4nidev"
    accent = "#00d1b2"
    showBorder = true
    backgroundColor = "#f7f4ef"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["javascript", "typescript", "html", "css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:mail@danidev.es"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/d4nidev/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/d4nidev/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/danidelacruz/"
    name = "linkedin"
    weight = 4
